<?=$this->extend('templates/default');?>
<?=$this->section('content');?>
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table id="purchase_order_table" class="table table-hover table-striped nowrap" width="100%">
                        <thead class="nowrap">
                            <tr> 
                                <th>Actions</th>
                                <th>Items</th>
                                <th>Status</th>
                                <th>PO ID</th>
                                <th>Supplier</th>
                                <th>Attention To</th>
                                <th>Requested By</th>
                                <th>Requested At</th>
                                <th>Generated By</th>
                                <th>Generated At</th>
                                <th>Received By</th>
                                <th>Received At</th>
                                <th>Filed By</th>
                                <th>Filed At</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<?= $this->include('purchasing/purchase_order/form'); ?>
<?= $this->include('purchasing/purchase_order/items'); ?>
<?= $this->include('templates/loading'); ?>
<?=$this->endSection();?>